version: '3.8'

services:
  rethinkdb:
    image: rethinkdb
    container_name: rethinkdb
    ports:
      - "8080:8080"  
      - "28015:28015"  
      - "29015:29015"  
    volumes:
      - rethinkdb_data:/data

  server:
    build: ./server
    container_name: todo-server
    ports:
      - "5000:5000"
    depends_on:
      - rethinkdb
    volumes:
      - ./server:/app
    environment:
      - NODE_ENV=production

  client:
    image: nginx
    container_name: todo-client
    ports:
      - "80:80"
    volumes:
      - ./client/public:/usr/share/nginx/html
    depends_on:
      - server

volumes:
  rethinkdb_data:
