version: '3.8'
services:
  rethinkdb:
    image: rethinkdb:latest
    ports:
      - "28015:28015"
      - "29015:29015"
    volumes:
      - rethinkdb_data:/data
    environment:
      RETHINKDB_DRIVER_TCP_BACKLOG: 512

  server:
    build:
      context: .   
      dockerfile: server/Dockerfile  
    ports:
      - "3000:3000"
    depends_on:
      - rethinkdb
    environment:
      - NODE_ENV=development
    volumes:
      - ./server:/app  

  client:
    build:
      context: ./client 
      dockerfile: Dockerfile  
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./client:/app  

volumes:
  rethinkdb_data:
